# Generated by Django 3.0.6 on 2020-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200512_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('IB', 'INBOUND'), ('OB', 'OUTBOUND'), ('WI', 'WALK IN'), ('FD', 'FOOD'), ('SM', 'SOCIAL MEDIA'), ('OT', 'OTHER')], default='OT', max_length=2),
        ),
    ]
